package com.xiaomi.imybatis.generator

import com.xiaomi.imybatis.database.ColumnMetadata
import com.xiaomi.imybatis.database.TableMetadata
import com.xiaomi.imybatis.template.TemplateEngine
import java.util.*

/**
 * Generator for Entity classes
 */
class EntityGenerator(private val templateEngine: TemplateEngine) {

    /**
     * Generate Entity class code
     */
    fun generate(
        tableMetadata: TableMetadata,
        packageName: String,
        className: String,
        useLombok: Boolean = true,
        useMyBatisPlus: Boolean = true
    ): String {
        val fields = tableMetadata.columns.map { column ->
            FieldInfo(
                name = camelCase(column.name),
                type = columnTypeToJavaType(column),
                columnName = column.name,
                primaryKey = column.isPrimaryKey,
                nullable = column.nullable,
                comment = column.comment
            )
        }

        val dataModel = mapOf(
            "packageName" to packageName,
            "className" to className,
            "tableName" to tableMetadata.name,
            "fields" to fields,
            "useLombok" to useLombok,
            "useMyBatisPlus" to useMyBatisPlus,
            "primaryKeys" to tableMetadata.primaryKeys,
            "date" to Date()
        )

        val template = getDefaultEntityTemplate()
        return templateEngine.processString(template, dataModel)
    }

    /**
     * Convert column name to camelCase
     */
    private fun camelCase(name: String): String {
        val parts = name.split("_")
        return if (parts.isEmpty()) name else {
            parts[0].lowercase() + parts.drop(1).joinToString("") { 
                it.lowercase().replaceFirstChar { char -> char.uppercaseChar() }
            }
        }
    }

    /**
     * Convert column type to Java type
     */
    private fun columnTypeToJavaType(column: ColumnMetadata): String {
        return when (column.type.uppercase()) {
            "INT", "INTEGER", "TINYINT", "SMALLINT", "MEDIUMINT" -> "Integer"
            "BIGINT" -> "Long"
            "DECIMAL", "NUMERIC" -> "java.math.BigDecimal"
            "FLOAT", "REAL" -> "Float"
            "DOUBLE" -> "Double"
            "BOOLEAN", "BIT" -> "Boolean"
            "CHAR", "VARCHAR", "TEXT", "MEDIUMTEXT", "LONGTEXT" -> "String"
            "DATE" -> "java.time.LocalDate"
            "TIME" -> "java.time.LocalTime"
            "DATETIME", "TIMESTAMP" -> "java.time.LocalDateTime"
            "BLOB", "BYTEA" -> "byte[]"
            else -> "String"
        }
    }

    /**
     * Get default Entity template
     */
    private fun getDefaultEntityTemplate(): String {
        return """
package ${'$'}{packageName};

<#if useLombok>
import lombok.Data;
import lombok.EqualsAndHashCode;
</#if>
<#if useMyBatisPlus>
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableField;
</#if>
<#if fields?filter(f -> f.type?contains("LocalDate") || f.type?contains("LocalDateTime") || f.type?contains("LocalTime"))?size gt 0>
import java.time.*;
</#if>
<#if fields?filter(f -> f.type?contains("BigDecimal"))?size gt 0>
import java.math.BigDecimal;
</#if>

/**
 * Entity class for table: ${'$'}{tableName}
 * Generated by imybatis
 */
<#if useLombok>
@Data
@EqualsAndHashCode(callSuper = false)
</#if>
<#if useMyBatisPlus>
@TableName("${'$'}{tableName}")
</#if>
public class ${'$'}{className} {
<#list fields as field>
    <#if field.comment??>
    /**
     * ${'$'}{field.comment}
     */
    </#if>
    <#if useMyBatisPlus>
    <#if field.primaryKey>
    @TableId
    </#if>
    <#if field.columnName != field.name>
    @TableField("${'$'}{field.columnName}")
    </#if>
    </#if>
    private ${'$'}{field.type} ${'$'}{field.name};
</#list>
}
        """.trimIndent()
    }
}

/**
 * Field information for template
 */
data class FieldInfo(
    val name: String,
    val type: String,
    val columnName: String,
    val primaryKey: Boolean,
    val nullable: Boolean,
    val comment: String?
)
