package com.xiaomi.imybatis.generator

import com.xiaomi.imybatis.template.TemplateEngine

/**
 * Generator for Mapper interfaces
 */
class MapperGenerator(private val templateEngine: TemplateEngine) {

    /**
     * Generate Mapper interface code
     */
    fun generate(
        packageName: String,
        mapperName: String,
        entityName: String,
        entityPackage: String,
        useMyBatisPlus: Boolean = true
    ): String {
        val dataModel = mapOf(
            "packageName" to packageName,
            "mapperName" to mapperName,
            "entityName" to entityName,
            "entityPackage" to entityPackage,
            "entityFqn" to "$entityPackage.$entityName",
            "useMyBatisPlus" to useMyBatisPlus
        )

        val template = getDefaultMapperTemplate()
        return templateEngine.processString(template, dataModel)
    }

    private fun getDefaultMapperTemplate(): String {
        return """
package ${'$'}{packageName};

import ${'$'}{entityFqn};
<#if useMyBatisPlus>
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
</#if>

/**
 * Mapper interface for ${'$'}{entityName}
 * Generated by imybatis
 */
<#if useMyBatisPlus>
@Mapper
public interface ${'$'}{mapperName} extends BaseMapper<${'$'}{entityName}> {
}
<#else>
public interface ${'$'}{mapperName} {
    // Add your custom methods here
}
</#if>
        """.trimIndent()
    }
}
