package com.xiaomi.imybatis.generator

import com.xiaomi.imybatis.template.TemplateEngine

/**
 * Generator for Service and Controller classes (MyBatis Plus style)
 */
class ServiceGenerator(private val templateEngine: TemplateEngine) {

    /**
     * Generate Service interface
     */
    fun generateServiceInterface(
        packageName: String,
        serviceName: String,
        entityName: String,
        entityPackage: String,
        useMyBatisPlus: Boolean = true
    ): String {
        val dataModel = mapOf(
            "packageName" to packageName,
            "serviceName" to serviceName,
            "entityName" to entityName,
            "entityPackage" to entityPackage,
            "entityFqn" to "$entityPackage.$entityName",
            "useMyBatisPlus" to useMyBatisPlus
        )

        val template = getDefaultServiceInterfaceTemplate()
        return templateEngine.processString(template, dataModel)
    }

    /**
     * Generate Service implementation
     */
    fun generateServiceImpl(
        packageName: String,
        serviceImplName: String,
        serviceName: String,
        servicePackage: String,
        mapperName: String,
        mapperPackage: String,
        entityName: String,
        entityPackage: String,
        useMyBatisPlus: Boolean = true
    ): String {
        val dataModel = mapOf(
            "packageName" to packageName,
            "serviceImplName" to serviceImplName,
            "serviceName" to serviceName,
            "servicePackage" to servicePackage,
            "serviceFqn" to "$servicePackage.$serviceName",
            "mapperName" to mapperName,
            "mapperPackage" to mapperPackage,
            "mapperFqn" to "$mapperPackage.$mapperName",
            "entityName" to entityName,
            "entityPackage" to entityPackage,
            "entityFqn" to "$entityPackage.$entityName",
            "useMyBatisPlus" to useMyBatisPlus
        )

        val template = getDefaultServiceImplTemplate()
        return templateEngine.processString(template, dataModel)
    }

    /**
     * Generate Controller
     */
    fun generateController(
        packageName: String,
        controllerName: String,
        serviceName: String,
        servicePackage: String,
        entityName: String,
        entityPackage: String,
        useMyBatisPlus: Boolean = true
    ): String {
        val dataModel = mapOf(
            "packageName" to packageName,
            "controllerName" to controllerName,
            "serviceName" to serviceName,
            "servicePackage" to servicePackage,
            "serviceFqn" to "$servicePackage.$serviceName",
            "entityName" to entityName,
            "entityPackage" to entityPackage,
            "entityFqn" to "$entityPackage.$entityName",
            "useMyBatisPlus" to useMyBatisPlus
        )

        val template = getDefaultControllerTemplate()
        return templateEngine.processString(template, dataModel)
    }

    private fun getDefaultServiceInterfaceTemplate(): String {
        return """
package ${'$'}{packageName};

import ${'$'}{entityFqn};
<#if useMyBatisPlus>
import com.baomidou.mybatisplus.extension.service.IService;

/**
 * Service interface for ${'$'}{entityName}
 * Generated by imybatis
 */
public interface ${'$'}{serviceName} extends IService<${'$'}{entityName}> {
    // Add your custom methods here
}
<#else>
import java.util.List;

/**
 * Service interface for ${'$'}{entityName}
 * Generated by imybatis
 */
public interface ${'$'}{serviceName} {

    ${'$'}{entityName} getById(Long id);

    List<${'$'}{entityName}> list();

    boolean save(${'$'}{entityName} entity);

    boolean updateById(${'$'}{entityName} entity);

    boolean removeById(Long id);
}
</#if>
        """.trimIndent()
    }

    private fun getDefaultServiceImplTemplate(): String {
        return """
package ${'$'}{packageName};

import ${'$'}{entityFqn};
import ${'$'}{serviceFqn};
import ${'$'}{mapperFqn};
<#if useMyBatisPlus>
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.springframework.stereotype.Service;

/**
 * Service implementation for ${'$'}{entityName}
 * Generated by imybatis
 */
@Service
public class ${'$'}{serviceImplName} extends ServiceImpl<${'$'}{mapperName}, ${'$'}{entityName}> implements ${'$'}{serviceName} {
    // Add your custom methods here
}
<#else>
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.List;

/**
 * Service implementation for ${'$'}{entityName}
 * Generated by imybatis
 */
@Service
public class ${'$'}{serviceImplName} implements ${'$'}{serviceName} {

    @Autowired
    private ${'$'}{mapperName} ${'$'}{mapperName?uncap_first};

    @Override
    public ${'$'}{entityName} getById(Long id) {
        return ${'$'}{mapperName?uncap_first}.selectById(id);
    }

    @Override
    public List<${'$'}{entityName}> list() {
        return ${'$'}{mapperName?uncap_first}.selectList();
    }

    @Override
    public boolean save(${'$'}{entityName} entity) {
        return ${'$'}{mapperName?uncap_first}.insert(entity) > 0;
    }

    @Override
    public boolean updateById(${'$'}{entityName} entity) {
        return ${'$'}{mapperName?uncap_first}.updateById(entity) > 0;
    }

    @Override
    public boolean removeById(Long id) {
        return ${'$'}{mapperName?uncap_first}.deleteById(id) > 0;
    }
}
</#if>
        """.trimIndent()
    }

    private fun getDefaultControllerTemplate(): String {
        return """
package ${'$'}{packageName};

import ${'$'}{entityFqn};
import ${'$'}{serviceFqn};
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * Controller for ${'$'}{entityName}
 * Generated by imybatis
 */
@RestController
@RequestMapping("/api/${'$'}{entityName?lower_case}")
public class ${'$'}{controllerName} {
    
    @Autowired
    private ${'$'}{serviceName} ${'$'}{serviceName?uncap_first};
    
    @GetMapping("/{id}")
    public ${'$'}{entityName} getById(@PathVariable Long id) {
        return ${'$'}{serviceName?uncap_first}.getById(id);
    }
    
    @GetMapping
    public List<${'$'}{entityName}> list() {
        return ${'$'}{serviceName?uncap_first}.list();
    }
    
    @PostMapping
    public boolean save(@RequestBody ${'$'}{entityName} entity) {
        return ${'$'}{serviceName?uncap_first}.save(entity);
    }
    
    @PutMapping
    public boolean update(@RequestBody ${'$'}{entityName} entity) {
        return ${'$'}{serviceName?uncap_first}.updateById(entity);
    }
    
    @DeleteMapping("/{id}")
    public boolean delete(@PathVariable Long id) {
        return ${'$'}{serviceName?uncap_first}.removeById(id);
    }
}
        """.trimIndent()
    }
}
